spring:
  application:
    name: product-service

  data:
    mongodb:
      uri: ${mongo_uri}
      database: ThePetClub
      auto-index-creation: true
      username: ${mongo_username}
      password: ${mongo_password}

access:
  key:
    id: ${access_key}
    secret: ${access_secret}
s3:
  region:
    name: ap-southeast-2
  bucket:
    name: skillifymestorage
api:
  prefix: api/v1

server:
  PORT: 8081

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

user-service:
  url: http://localhost:8080 #%20Replace%20with%20the%20actual%20URL%20of%20your%20USER-SERVICE
